inherit_from: .rubocop_todo.yml
AllCops:
TargetRubyVersion: 3.0
  Exclude:
    - '**/scripts/**/**/**/*'
    - 'vendor/**/*'
    - '**/tmp/**/*'
    - '**/db/data/**/*'
    - '**/db/data_schema.rb'
    - '**/db/schema.rb'
    - '**/bin/**/*'
    - '**/node_modules/**/*'
    - 'guides/**/*'
Documentation:
  Enabled: false